### ISSUE TITLE
[Enhancement] Can't unpin project

### ISSUE THREAD

**Issue by yuriatgoogle** [GoogleCloudPlatform/cloud-code-vscode#23]
I'd like to remove a project from the treeview:

![image](https://user-images.githubusercontent.com/26609620/53366626-e6fe9680-38f8-11e9-95d8-36b44f39950e.png)

I can unpin the second project:
![image](https://user-images.githubusercontent.com/26609620/53366683-0bf30980-38f9-11e9-8665-69964d4608cb.png)

But not the first?
![image](https://user-images.githubusercontent.com/26609620/53366713-157c7180-38f9-11e9-83b1-97ea1d7ffe9f.png)

**Comment by sivakku** [comment]
We moved to listing only one project in the explorer, so that there is consistency with all other web views and with a default project that all flows would take consume it, this would simplify the flows with gcloud as well. The switch project next to the project in explorer helps to select a different project.
