### ISSUE TITLE
Cloud Run Explorer hangs if API is not Enabled. No Warning.

### ISSUE THREAD

**Issue by fabltd** [GoogleCloudPlatform/cloud-code-vscode#240]
**Environment**:
Extension version: 1.3.0
VSCode version: 1.45.1
OS: darwin

**Description**:

Cloud run explorer hangs if the API is not enabled. 

**Repro step**:

Setup new project try to explore for Cloud Run instances. Progress bar just keeps going and the run icon shows a little clock.

**Comment by redborian** [comment]
Thanks for reporting this issue @fabltd. I am able to repro this issue. This will be part of the upcoming Cloud Code release.

**Comment by haplm** [comment]
Guys, I'm running minikube locally, with API available at http://localhost:8080/api/ using
kubectl proxy --port=8080. This is apparently not enough to workaround the issue reported above  (I too see progress bar going indefinitely). Is there something I can to in the meantime before the fix is released? Thanks!

**Comment by redborian** [comment]
This has been fixed in the latest release. Please update to the latest version.
