### ISSUE TITLE
Cloud Run Deploy does not list existing CRoA services

### ISSUE THREAD

**Issue by marcfong** [GoogleCloudPlatform/cloud-code-vscode#272]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.4.1
VSCode version: 1.45.1
OS: Mac

**Description**:
Cloud Run Deploy does not list existing Cloud Run on Anthos services in the current project.

**Repro step**:

1. Either deploy a new CRoA service via cloud console or via Cloud Code.
2. In CC VSCode, choose "Cloud Run > Deploy" action
3. Under the section "Service settings" and the dropdown "service" , you will not be able to see existing CRoA services listed in the dropdown. Even after changing the "deployment platform" to "CLoud Run for Anthos"lower in the page, the existing services in the project do not show up.

Note: by deploying again to the exact same service name and namespace, a new revision to the existing service gets created.

**Comment by kschaab** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2819)

**Comment by kschaab** [comment]
@marcfong - we are unable to reproduce this issue, cloud run services deployed on anthos are listed.  Since you say that you are redeploying by reusing the same settings it's not something obvious.  Not that it is necessary, are you deploying to the default namespace?  Does the service show up for your logged in account in the GCP console?  Any additional details you can provide might be helpful.

**Comment by jmah-cc** [comment]
Please re-open with additional details if you're still able to repro this issue.
