### ISSUE TITLE
Cloud Run fully managed users may not know which builder to choose

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-code-vscode#296]
Developers may not know which builder to choose (Buildpacks vs Docker vs Jib). 

Possible solution: This information could be hidden in advance settings and automatically inferred based on the project.

**Comment by jmah-cc** [comment]
After reviewing this ask again, it's not at the top of our priority list. We've added it to our Backlog. Leaving this issue open so other users can upvote this request.

**Comment by sivakku** [comment]
@averikitsch - The feature is in the advanced settings(we just expanded that section, so they see before deploying but otherwise would have been hidden). it picks a default builder that the user doesn't have to pick it up if they are deploying based on a docker file exist or not in the project.  

![image](https://user-images.githubusercontent.com/16199637/104070247-5020e780-51bb-11eb-8388-5d33bdce4820.png)

**Comment by vincentjocodes** [comment]
We'll close this one due to inactivity. Please feel free to open it back up again if you have any more concerns.
