### ISSUE TITLE
gcloud installed in /usr/local/bin but extension says not found

### ISSUE THREAD

**Issue by Morriz** [GoogleCloudPlatform/cloud-code-vscode#315]
I would expect the extension to work with what is found in path, or at least provide an option to point to it.

**Environment**:

Extension version: v1.6.1
VSCode version: 1.50.1
OS: OSX

**Description**:

I installed gcloud with brew

**Repro step**:

install with `brew install google-cloud-sdk`
start vscode

**Comment by go-nelango** [comment]
@Morriz does `which gcloud` return the path correctly?

**Comment by Morriz** [comment]
Of course, did that not become clear from the title?

**Comment by go-nelango** [comment]
Have you turned off Auto Dependencies in the extension settings? What is your gcloud version?

**Comment by kschaab** [comment]
@Morriz assuming that you have Automatic Management of Dependencies turned on there might be an issue that is causing this problem for you, does it disappear if you close VS Code and reopen?  If you do not have automatic management of dependencies turned on I would have to assume that VS Code cannot find `gcloud` in `/usr/local/bin` which would be very odd indeed.

**Comment by Morriz** [comment]
I don't know why it does not find my `/usr/local/bin/gcloud` over and over again, so if somebody would like to look into this, please do. I have multiple issues with the gcloud installer not using PATH (But that might be unrelated here. See https://issuetracker.google.com/issues/171493249. Unfortunately google did decide to NOT use github for that code.)

@go-nelango as to your suggestion to turn off Auto Dependencies: I would like to use that feature. Are you asking to deduce what could be buggy?

**Comment by kschaab** [comment]
@Morriz - Turning off auto dependencies can be done through the preferences UI in Visual Studio Code:

![image](https://user-images.githubusercontent.com/7329029/99475010-7c7a5f00-2902-11eb-883f-8ec2a42c8f58.png)

Since you do have dependency management on, I wonder why we aren't finding the dependency.  On Mac there should be a version of gcloud installed here:  `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk` which is the version that we should be using (not the one installed by brew).

Sorry about not responding earlier, I missed your reply.

**Comment by Morriz** [comment]
> On Mac there should be a version of gcloud installed here: `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk` which is the version that we should be using (not the one installed by brew).
> 

Why? Why can't it use the one in the $PATH?

**Comment by kschaab** [comment]
It can use the one in the path if you turn off automatic management of dependencies.
