### ISSUE TITLE
Cloud Code on M1 Macs: Known issues

### ISSUE THREAD

**Issue by robkelly** [GoogleCloudPlatform/cloud-code-vscode#390]
With the March 2021 release of Cloud Code for VSCode, we’re pleased to announce initial support for M1-based Apple Silicon Macs. With this update, you can now build and work locally with Cloud Code, minikube, and Skaffold for ARM64 targets on your M1 Mac. Please note that Rosetta 2 is currently required as several dependencies are still x86/64 only.

If you run into any scenarios that don’t work quite right for you, please file an issue on GitHub so we can investigate.

### Note on x86 image support
Docker defaults to building for your local architecture (ARM64 for M1-based Macs), and cross-architecture build support for x86 is still in technical preview and has not been found to be sufficiently robust. Until this support is finalized, we recommend building images remotely through your CI/CD system, Kaniko, or Google Cloud Build. Other Docker-based image builders, such as the Buildpacks image builder, are impacted as well. Image builders such as Jib and Ko are not impacted though may require additional configuration. Bazel support depends on the rule sets used.

As of version 1.12.0, Cloud Code will default to using Google Cloud Build as the build environment when setting up a new Skaffold file or deploying to Cloud Run. If you have an existing Skaffold file, Cloud Code will prompt you change your Skaffold profile manually to use a compatible build environment. For more information on how to configure Skaffold build environment, see the [Skaffold docs](https://skaffold.dev/docs/pipeline-stages/builders/).

### Known issues for VS Code extension that we're working on:

- Using buildpacks will result in build errors and is therefore not suggested by Cloud Code as a builder. Use Dockerfiles or Jib builds instead. (tracking in https://github.com/GoogleCloudPlatform/buildpacks/issues/112)
- Cloud Run emulator segfaults (tracking in https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/389)

**Comment by sivakku** [comment]
Closing this one since we have M1 support available in plugin, there are some improvements coming in later release and if you have some feature that you like to see on Cloud Code for M1, do raise a GitHub ticket.

**Comment by ryan-efendy** [comment]
@sivakku If we're on the M1 (rosetta 2 installed) and we enabled auto dependencies where does Cloud Code install the command-line dependencies?

Asking because I also installed Cloud SDK, Skaffold, minikube manually to target the ARM version. So I want to uninstall/remove the non ARM versions and prevent having multiple architectures versions on my machine.

**Comment by robkelly** [comment]
Hi Ryan,

The dependencies on Mac all get installed to ~/Library/Application\ Support/cloud-code/installer/google-cloud/sdk/bin

**Comment by TenzinChang** [comment]
Is cross-architecture build available for native Cloud Run + Docker (on M1 Mac/VSCode)? I remember reading somewhere Skaffold/Kubernetes will automatically build x86 when deploying to Cloud Run, but I'm testing hello-world Java, the local "Cloud Run Emulator" worked (armx64) but when I tried "Deploy To Cloud Run" with Docker, it got stuck in Build #10, I suspect it's because it still has trouble building on x86?
