### ISSUE TITLE
Timeout waiting for GCP-Auth pods

### ISSUE THREAD

**Issue by cayden-uw** [GoogleCloudPlatform/cloud-code-vscode#441]
**Environment**:
Golang Cloud run project

**Version information**
Golang:  1.16.2

Cloud Code Extension version: 1.12.1

VSCode version: 1.57.1

OS: Ubuntu 21.04 x86_64

- Managed Dependencies: on
- Cloud SDK Version: 346.0.0
- Skaffold Version: v1.26.1
- Minikube Version: 1.21.0

**Description**:
While trying to debug a cloud run project I consistently get a failure settings up the gcp-auth addon

**Workarounds attempted**:

- Remove cloud-run-dev-internal container
- Remove all minikube images 
- Restart docker
- Restart computer

**Repro step**:

1. Remove all existing minikube images and containers from docker
2. Run Debug on cloud run emulator 
3. Wait >5 minutes

Logs: 
I0623 18:04:52.824719  130983 addons.go:135] Setting addon gcp-auth=true in "cloud-run-dev-internal"
I0623 18:04:52.824737  130983 addons.go:313] Verifying addon gcp-auth=true in "cloud-run-dev-internal"
I0623 18:04:52.827436  130983 out.go:170] * Verifying gcp-auth addon...
I0623 18:04:52.832597  130983 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=gcp-auth" in ns "gcp-auth" ...
I0623 18:04:52.844446  130983 kapi.go:86] Found 0 Pods for label selector kubernetes.io/minikube-addons=gcp-auth
I0623 18:10:52.850078  130983 kapi.go:108] duration metric: took 6m0.017485354s to wait for kubernetes.io/minikube-addons=gcp-auth ...
I0623 18:10:52.854725  130983 out.go:170] 
W0623 18:10:52.854870  130983 out.go:235] X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=gcp-auth pods: timed out waiting for the condition]

**Comment by cayden-uw** [comment]
I have now got this working. My workaround was:

1. `minikube delete --all`
2. Delete the existing minikube images from docker 

I had tried deleting all the docker images, networks and containers, but this did not seem to do the trick.
After running`minikube delete --all` the first time and not removing the existing minikube images from docker, I got an error saying the context of cloud-run-dev-internal did not exist. Repeating this process and deleting the images seemed to fix it all up.

**Comment by ssmall** [comment]
Hi @cayden-uw ,thanks for linking this issue with https://github.com/kubernetes/minikube/issues/11565 -- it appears that the root cause is probably on the minikube side, but I'm glad you were able to identify a workaround to unblock yourself for now. If you encounter the issue again, please consider trying the following:

Go to Settings and search for `cloudcode.enableMinikubeGcpAuthPlugin`, then uncheck the box and try debugging again?

It would also help if you could enable verbose logging in the settings as well (`cloudcode.verboseLogging`) and share any relevant logs.
