### ISSUE TITLE
Breakpoints work intermittently with Go Cloud Run debugging

### ISSUE THREAD

**Issue by cayden-uw** [GoogleCloudPlatform/cloud-code-vscode#445]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

- Managed Dependencies: on
- Cloud SDK Version: 347.0.0
- Skaffold Version: v1.26.1
- Minikube Version: 1.21.0
**Version information**

Cloud Code Extension version:  1.13

VSCode version: 1.57.1

OS:  Ubuntu 21.04 x86_64

Cloud SDK: 347.0.0

Skaffold: v1.26.1

**Description**:

I get an error "Failed to halt delve before attempting to set breakpoint: "Process 12 has exited with status 0"" around 9 times out of 10 when I try to set a breakpoint when using the Cloud Run; debug locally option. 

My cloud run project is using go

**Repro step**:
1. Run cloud run; debug locally 
2. Add a breakpoint 

// Note this may work once per run, but after a crash or updating code it will not work

**Additional information**:
Logs from Cloud Run :Run/Debug - Detailed : 

Starting deploy...
Artifact \"server\" has Go runtime: has env \"GOTRACEBACK\"
Configuring \"server-container\" for Go/Delve debugging
\"server-container\" requires debugging support image \"go\"
Configuring installation of debugging support files
 - deployment.apps/server created
 - service/server created
Deploy completed in 652.219597ms
Waiting for deployments to stabilize...
 - deployment/server is ready.
Deployments stabilized in 4.679 seconds
Press Ctrl+C to exit
Watching for changes...
Streaming logs from pod: server-5846cf9956-5wdf2 container: server-container
Streaming logs from pod: server-5846cf9956-5wdf2 container: install-go-debug-support
[install-go-debug-support] Installing runtime debugging support files in /dbg
[install-go-debug-support] Installation complete
[server-container] API server listening at: [::]:56268

Please let me know what additonal information would be helpful

**Comment by quoctruong** [comment]
@cayden-uw Is it possible to share a small sample application that can repro the issue?

**Comment by sivakku** [comment]
@cayden-uw - We weren't able to reproduce, it would be great if you can help us craft a repro that we can use. Thanks for the feedback. Please re-open once you add the steps to repro.

**Comment by cayden-uw** [comment]
Hi @quoctruong and @sivakku, 

Sorry for the slow reply. I was able to repro today again. The same image works on cloud run in production and it seems that I can, without code changes, get this same build working locally. 

I seem to get 4 states:
1. It runs locally without the triggering of break points
2. It runs locally but doesn't work and breakpoints won't trigger, no error apart from the first line below
3. It crashes as per the lines below
4. It runs and breakpointing works

These are the log lines that seem relevent. The logs show these occur on the running of grpc server. 

[server-container] 2021-07-20T00:30:40Z error layer=rpc writing response:write tcp 127.0.0.1:56268->127.0.0.1:36482: use of closed network connection
[server-container] fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x44f12e]

**Comment by ssmall** [comment]
Hi @cayden-uw,

A couple things to point out here:

> I have been putting a breakpoint on the very first line of main()

There is a bit of a race condition with this. Chances are that by the time the debugger connects to your process, the program execution has already proceeded beyond the first line of `main`. I can practically guarantee this is the case with the Cloud Run emulator, because it performs health checks to make sure that the process is running and listening on the expected port before it tries to connect the debugger.

> Adding a 20 second sleep as the first line of main seems to increase the likelihood of successfully running and breaking pointing.

You're much better off setting a break point on a code path that you can manually trigger (something that you know gets called repeatedly in a loop, or something that is triggered by an external request).

The stack trace you shared looks a lot like a TCP timeout that is not being handled correctly somewhere in the code. This can be a pretty common occurrence when debugging server code that is serving requests via TCP (e.g. HTTP, gRPC, etc) -- anything that halts execution of the goroutine processing the request can easily trigger TCP timeouts.

Without access to your source code, I can make the following general suggestions:
1. if you are able to, temporarily override TCP read and write timeouts for your application ([pure Go](https://pkg.go.dev/net#Conn), [gRPC](https://grpc.io/blog/deadlines/))
2. it also sounds like when a timeout occurs, it is not always crashing the entire process. This is the kind of failure scenario where you _want_ the whole process to crash, because then it will get automatically restarted by the Cloud Run emulator/runtime. Instead, what I suspect might be happening is that the goroutine which listens for incoming requests is crashing but the overall server process is still running, leading to the second scenario you observed above.

Again, these are just guesses based on the information you have provided. The more detail you are able to provide, the better we will be able to assist. It would be very helpful to get the following details:

1. how are you triggering the code where you have set the breakpoint? Is it a manual HTTP call, gRPC request, or something else?
2. if you proceed immediately after hitting the breakpoint (try to catch it the moment it hits and just allow the execution to proceed) do you still see any issues?
3. I understand you may be restricted in what you are able to share publicly, but if there is any way you are able to make a screen recording to demonstrate reproducing this issue, it would be very helpful to help us diagnose the possible root cause(s)

**Comment by cayden-uw** [comment]
Hi @ssmall, 

Thanks for the really thorough reply! 

> There is a bit of a race condition with this. Chances are that by the time the debugger connects to your process, the program execution has already proceeded beyond the first line of main. I can practically guarantee this is the case with the Cloud Run emulator, because it performs health checks to make sure that the process is running and listening on the expected port before it tries to connect the debugger.

That makes a tonne of sense as to why it is a bit flakey for early breakpoints! 

> The stack trace you shared looks a lot like a TCP timeout that is not being handled correctly somewhere in the code. This can be a pretty common occurrence when debugging server code that is serving requests via TCP (e.g. HTTP, gRPC, etc) -- anything that halts execution of the goroutine processing the request can easily trigger TCP timeouts.

I dug into this a little more based on the stacktrace I shared and your thoughts on it being TCP timeout related. If I set line 1 of main to sleep, the crash would occur before the sleep ran out. This is before any inbound or outbound TCP requests are triggered. Is it logged anywhere is cloud run kills the process due to a timeout or similar? 

I am not sure where the opencensus piece comes from (cloud run triggers it automatically perhaps?)

> how are you triggering the code where you have set the breakpoint? Is it a manual HTTP call, gRPC request, or something else?

Grpc request

> if you proceed immediately after hitting the breakpoint (try to catch it the moment it hits and just allow the execution to proceed) do you still see any issues?

It seems if I can get a breakpoint, it will work from then on. The primary problem seems to be the service SIGSEGV'ing before anything meaningful can happen.  

> I understand you may be restricted in what you are able to share publicly, but if there is any way you are able to make a screen recording to demonstrate reproducing this issue, it would be very helpful to help us diagnose the possible root cause(s)

I could jump on a quick call and screenshare if that helps?

**Comment by ssmall** [comment]
Hi @cayden-uw,

Sure, I'd be happy to hop on a call. If you haven't already, go ahead and join our [Slack](https://join.slack.com/t/googlecloud-community/shared_invite/zt-m973j990-IMij2Xh8qKPu7SaHfOcCFg) -- once you've joined we can exchange contact information via DM to set up a call.

> If I set line 1 of main to sleep, the crash would occur before the sleep ran out. This is before any inbound or outbound TCP requests are triggered. Is it logged anywhere is cloud run kills the process due to a timeout or similar?

I would want to verify this to be sure, but what could be happening here is that the Cloud Run Emulator (which is minikube under the hood) will kill the container and restart it if it doesn't start listening on the expected port within a certain number of seconds. So there are two timeouts at play:
1. the container has to begin accepting requests on the expected port within a certain timeout or it is considered "unhealthy" and will be restarted
2. any TCP connection is subject to socket timeouts

**Comment by sivakku** [comment]
Please reach out to us on slack if you are seeing any issue that need to be addressed, the link to Slack is on the Readme. Thanks!

**Comment by luisignaciomenendez** [comment]
> Please reach out to us on slack if you are seeing any issue that need to be addressed, the link to Slack is on the Readme. Thanks!

Hello, is there any way to join the slack group without having a google account? If so could you please send me an invitation to luisignaciorionora@gmail.com ?
Thanks!
