### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by superyass** [GoogleCloudPlatform/cloud-code-vscode#446]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.13.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ZVHK4603\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sivakku** [comment]
@superyass -  Can you attach the require cpu profile(c:\Users\ZVHK4603\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt) that is highlighted in the bug? Please re-open once you updated it.

**Comment by tuzi3040** [comment]
I have the same issue.
Both 1.13.1 and 1.13.0 have this problem. Downgrade to 1.12.1 can temporarily resolve this.
I don't have google-cloud-sdk installed on this machine, because this extension is synced from my macbook pro which have google-cloud-sdk installed.

- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.13.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

The cpuprofile is attached below.
[googlecloudtools.cloudcode-unresponsive.cpuprofile.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/6873657/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt)

**Comment by tuzi3040** [comment]
@sivakku

**Comment by tuzi3040** [comment]
#452

**Comment by sivakku** [comment]
Thanks @tuzi3040 - we will address that issue in the next release at the end of August.

**Comment by ssmall** [comment]
Resolving this in favor of #452
