### ISSUE TITLE
choosing Debug on Kubernetes after terminating a Run on Kubernetes session still displays Run on Kubernetes at the top of the Development Sessions pane

### ISSUE THREAD

**Issue by kourtneyshort** [GoogleCloudPlatform/cloud-code-vscode#492]
**Environment**: Chromebook
**Version information**

Cloud Code Extension version: Cloud Code v 1.16.0-insiders.4

VSCode version:

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.151-16903-g4ff33e652e6f

OS: Chromebook

Cloud SDK: 355.0.0

Skaffold: 1.19.0

Kubectl: 1.20.2

**Description**:

Choosing Debug on Kubernetes after terminating a Run on Kubernetes session still displays Run on Kubernetes at the top of the Development Sessions pane

**Repro step**:
1. Clone a sample application.
2. Choose the Run on Kubernetes action.
3. Stop Run on Kubernetes.
4. Choose the Debug on Kubernetes action
Expected result:
The development pane says "Debug on Kubernetes"
Actual result:
The development pane still says "Run on Kubernetes"

**Comment by sujit-kamireddy** [comment]
@kourtneyshort , this is by design. What you are seeing in the Development Sessions explorer is the name of the launch configuration, which is "Run on Kubernetes". The same launch config is used for both running and debugging. You can change the name by clicking the Settings action on the "Run on Kubernetes" node.

We use a different icon (play vs debug) in the "Run on Kubernetes" node to distinguish b/w run and debug.

**Comment by vincentjocodes** [comment]
@kourtneyshort Hopefully @sujit-kamireddy 's answer make sense for you? If it doesn't please open this again and keep chatting! Thanks!
