### ISSUE TITLE
Run stop doesn't clean up resources

### ISSUE THREAD

**Issue by pentago** [GoogleCloudPlatform/cloud-code-vscode#519]
**Environment**:

all latest:
- MacOS 12.1 on Macbook Pro M1
- Docker for Mac
- Skaffold
- VS Code Insiders

**Description**:

When stopping the skaffold project, resources aren't deleted as it should be by default.

My [skaffold.yaml](https://gist.github.com/pentago/313fe01d6b8542f9767a53e09ed72041)

My project config:
![VS Code settings](https://i.imgur.com/bVkSrzu.png)

Stop function outcome:
![](https://i.imgur.com/DRQ6RMc.png)

Not sure why it tries to cleanup `k8s/*.yaml` if `skaffold.yaml` uses `kusotmize` and completely different paths.
Any ideas?

**Comment by ssmall** [comment]
> Not sure why it tries to cleanup k8s/*.yaml if skaffold.yaml uses kusotmize and completely different paths. Any ideas?

It looks like `k8s/*.yaml` is the default value when nothing is specified for `deploy.kubectl.manifests` in `skaffold.yaml`. However, given that you are using Kustomize for deployment I am not sure why this is the error that is being reported by Skaffold rather than using Kustomize for the cleanup stage. I am reaching out to the Skaffold devs to see if they have some insight about what could be going wrong here.

**Comment by ssmall** [comment]
@briandealwis had some insight here. It appears that you're seeing this behavior because all the configuration is happening in profiles and there is no root configuration in your `skaffold.yaml`. Skaffold sees that there is no root configuration and uses a default configuration before overriding settings based on the profile.

Can you try adding the following at the root level of your `skaffold.yaml`?

```yaml
deploy:
   kustomize: {}
```

**Comment by glouischandra** [comment]
@pentago does the yaml setting above resolve the issue? Feel free to reopen this bug if you're still having problem. Thanks!

**Comment by pentago** [comment]
@glouischandra not sure TBH, I changed my [skaffold.yaml](https://gist.github.com/pentago/801e0492ac0f011e7ad4e2754044671e) a bit and it works for me as intended.
