### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by jhonospina** [GoogleCloudPlatform/cloud-code-vscode#541]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:  1.17.0

VSCode version: 1.64.2

![image](https://user-images.githubusercontent.com/82119112/156183566-febc7f6b-d0de-4a72-a1f2-82674a69b3b6.png)

OS:  Windows 10

Cloud SDK: 374.0.0

Skaffold: 1.36.0

Kubectl:  1.21.9

![image](https://user-images.githubusercontent.com/82119112/156184706-8842903b-240d-4730-8e48-bd5d421b8c32.png)

**Description**:  I have problems deploying my sources in the GCP service: "cloud run", the visual studio code plugin "Cloude code" gives me the following message, when deploying:

![image](https://user-images.githubusercontent.com/82119112/156184168-e0ff7e31-4dc1-4a4f-9d5e-ff68a6974fcd.png)

**Repro step**:

**Comment by glouischandra** [comment]
Hello @jhonospina mind filling in the version information above so we can debug this issue better? Also the Report Extension Issue on Github link: 
![image](https://user-images.githubusercontent.com/3677364/156064186-4e5c24d6-3026-4f4a-9c02-8ecf966efb23.png)

Would automatically fill in the information for you.

**Comment by jhonospina** [comment]
My comments at the top!

thank you

**Comment by ssmall** [comment]
Hi @jhonospina,

Can you please confirm whether you have Auto Dependencies enabled? To do this, you can open Settings and search for `cloudcode.autoDependencies`:

![auto dependencies setting](https://user-images.githubusercontent.com/641091/156838392-527008c5-853b-44ae-85e9-28a8a84996df.png)

**If it is currently set to "off", try changing it to "on" and then reloading VS Code.**

**If it is already set to "on", please follow these steps:**
1. Enable Verbose Logging (setting id: `cloudcode.verboseLogging`)
![Verbose logging](https://user-images.githubusercontent.com/641091/156839504-4d32bc7f-d2eb-4a8d-948f-93872be577f3.png)
1. Change to Insider channel (setting id: `cloudcode.updateChannel`) -- this is necessary at the moment because there is a bug in 1.17.0 that affects verbose logging on Windows and macOS.
![Insiders channel](https://user-images.githubusercontent.com/641091/156839537-580ccbd3-a581-4652-b4ee-db9a575f83f0.png)
1. Reload VS Code when prompted
1. Confirm that Managed Dependency Installation completes successfully. If it fails, continue to the next step.
1. Open "Cloud Code" in the VSCode Output Panel
![Cloud Code in Output Panel](https://user-images.githubusercontent.com/641091/156839165-94c5ea0e-0fd3-454b-bbaa-3ad5fa59ccdf.png)
1. Copy output from the Cloud Code log and include it in your reply

**Comment by kschaab** [comment]
Closing due to lack of response
