### ISSUE TITLE
Cloud Code Login support without Browser

### ISSUE THREAD

**Issue by glouischandra** [GoogleCloudPlatform/cloud-code-vscode#607]
On VSCode running on Remote machine without access to browser should have the ability to use --no-browser flag within Cloud Code to login. 

Current Workaround is:
1. Open terminal within the VSCode remote session and issue: `gcloud auth login --no-browser`
2. Copy and paste the gcloud command outputted into another machine with access to gcloud and a browser
3. This command will output a URL, copy and paste this output into the VSCode remote session terminal 
4. Cloud Code should be logged in 

More information can be found in https://cloud.google.com/sdk/docs/authorizing

**Comment by Ark-kun** [comment]
It would be great if the support came in the form of a AuthenticationProvider https://code.visualstudio.com/api/references/vscode-api#AuthenticationProvider . This way multiple extensions can use it.

I also wish the authentication was pure JS instead of gcloud CLI. This way the extension works in VSCode web.

**Comment by kschaab** [comment]
This is being fixed in gcloud which will fix no browser support.  We don't support authentication provider as it is scoped in a way that would require the authentication to be owned by VS Code and it causes issues with ADC as this is machine wide.

**Comment by Ark-kun** [comment]
>issues with ADC as this is machine wide

Note, that VSCode Web is hermetic and browser-based, so there are no machine-wide ADC
