### ISSUE TITLE
Sync-up isn't happening

### ISSUE THREAD

**Issue by blessedwithsins** [GoogleCloudPlatform/cloud-code-vscode#639]
Type: <b>Bug</b>

*Context*

I am usingt his extension to manage my GKE Clusters. However, when a cluster is deleted, it doesn't sync well and there is no option to remove it as well from the extension viewer. 

- Managed Dependencies: on
- Cloud SDK Version: 399.0.0
- Skaffold Version: v1.39.1
- Minikube Version: 1.26.1

Extension version: 1.20.1
VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|--crash-reporter-id 5f7c9bf6-297b-4268-b0ed-1211df6bf66c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by blessedwithsins** [comment]
![Uploading Screen Shot 2022-08-25 at 8.00.10 AM.png…]()

**Comment by glouischandra** [comment]
Hi @blessedwithsins 

The kubernetes explorer is synced to the KubeConfig at the top of the explorer and in order to remove the context you can right click on the context and choose "Remove context under cluster". 

![image](https://user-images.githubusercontent.com/3677364/186732701-228f669e-4b7c-4be0-a6e5-a31efd197f03.png)

**Comment by blessedwithsins** [comment]
@glouischandra I am not getting this option at all. Attached is the snippet for same.

<img width="883" alt="Screen Shot 2022-08-26 at 9 26 22 AM" src="https://user-images.githubusercontent.com/26162427/186814279-93e38d84-91f8-4e0e-9942-66adf5fdcab3.png">

**Comment by glouischandra** [comment]
Thanks for the screenshot, the extension doesn't allow deletion of current active context (it has the chevron to the left of the red icon) but since you only have one context you have two options:
1. Add a new cluster context by using the plus button on the top of the K8s explorer and then you can delete the old cluster
2. Edit your kubeconfig and delete the context (and active context) from the file, however this leads you back to our zero state: 
![image](https://user-images.githubusercontent.com/3677364/186957170-3872080a-f6f1-404d-85d7-33a34cff5e02.png)
and you have to add a new cluster anyway. 

So I would recommend option 1 if possible.

**Comment by blessedwithsins** [comment]
@glouischandra This can be closed now. I don't get an option to remove the cluster using extension. I am cleaning up the config file to remove the clusters. 

This can be closed now.
