### ISSUE TITLE
Unable to run .NET Hello World sample

### ISSUE THREAD

**Issue by francotiveron** [GoogleCloudPlatform/cloud-code-vscode#669]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 407.0.0
- Skaffold Version: v1.39.3
- Minikube Version: 1.27.0
-Load the same
-Click on run on kubernetes as per instructions
-At a certain point VS code asks for "Choose Image Repository (1/1)"
-write the repository
-Press Enter. This should continue the process, instead nothing happens and it gets stuck here

Extension version: 1.20.3
VS Code version: Code - Insiders 1.73.0-insider (3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709, 2022-10-27T21:34:51.585Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (36.79GB free)|
|Process Argv|--crash-reporter-id 069701b0-35c0-493b-b96d-091de8b8f40e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30598410
j6j51389:30596843

```

</details>

![image](https://user-images.githubusercontent.com/8280970/198753923-787ea12a-c90a-4522-99a8-9d423d4b1304.png)

**Comment by ChaseMor** [comment]
There are definitely some user design things that can be done here that we can fix, but this flow is _technically_ working as intended. When you see this popup, it's actually a quick pick to select which type of Image Repository you'd like to use. It takes a few seconds to load (because some items may or may not appear in the list depending on the project) but it should show the options for selecting an image repository.

- Google Container Registry (gcr.io)
- [Artifact Registry](https://cloud.google.com/artifact-registry) (if the user has the Artifact Registry API enabled)
- A custom image repository (what you're looking for)

The default behavior of VS Code Quick Picks allows this text box to filter the results which isn't super helpful in this specific case. So it looks like what is happening is that you are entering in the custom url in the filter box which filters out those three options.

What happens if you wait a bit for these options to populate, select the custom repository option, and then enter in your url?

**Comment by francotiveron** [comment]
1. It asks for a context
![image](https://user-images.githubusercontent.com/8280970/199353841-aca587e5-3272-41e1-8624-726a7c088407.png)
2. After few seconds, it asks to enter repo
![image](https://user-images.githubusercontent.com/8280970/199353956-34cefce0-690b-425c-bd98-fc0c419581e3.png)
3. I waited here for 2 minutes, but it seems waiting for my input. 
4. Go to initial post

**Comment by ChaseMor** [comment]
Ah, I see. In many cases, users will see an option to use Google Container Registry if they have a context that is using GKE. In this specific case in which you are not, only one option appears which says `Enter the address of an image repository`. This is actually a button which is usually more apparent when there are more choices. If you click this option, it should take you to an input box that allows you to type in the exact address.

**Comment by francotiveron** [comment]
Works, thank you
