### ISSUE TITLE
Extension eventually crashes VSCode with `oidc-login`

### ISSUE THREAD

**Issue by jtagcat** [GoogleCloudPlatform/cloud-code-vscode#676]
1. kubectl authenticates the following to get credentials: `kubectl oidc-login get-token --listen-address=127.0.0.1:27890 --oidc-issuer-url=https://dex.codemowers.eu --oidc-client-id=kubelogin`

Expected: Browser is launched for authentication

Actual: `cloud-code-vscode` loads indefinitely. No browser is launched, nothing. After `oidc-login` timeouts, VSCode crashes.

**Comment by davidponder** [comment]
Hey @jtagcat thank you for the patience! Could you try the following:

In VS Code, set the "Cloudcode: Auto Dependencies" setting to off. This should cause Kubectl to use your locally installed instance of Kubectl, where oidc should succeed.
![image](https://user-images.githubusercontent.com/22482315/202326756-e6e1cf0e-ea50-4f59-98ce-0a89837829d8.png)

Please let us know what the outcome is, thanks!

**Comment by jtagcat** [comment]
@davidponder With Auto Dependencies off:

![image](https://user-images.githubusercontent.com/38327267/202515827-f25125db-8833-4abb-b8bc-7338e5c6bbe4.png)

`kubectl-oidc_login` is (as before) in PATH (under `~/.kube/krew/bin`)

![image](https://user-images.githubusercontent.com/38327267/202516162-3c2a30a1-95cd-4a13-a685-01290ea723fe.png)

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/202517146-78765c7e-c2ce-4563-8824-c48d8362b31e.png)

Tried using `kubectl-oidc_login` directly as well (instead of through `kubectl`), it is in `$PATH`:

![image](https://user-images.githubusercontent.com/38327267/202517694-b3f72253-6d45-4aae-894b-78b93e52c8a0.png)

Yet not picked up.

**Comment by jtagcat** [comment]
@davidponder that got me to this:

![image](https://user-images.githubusercontent.com/38327267/202518740-258e9e97-15c3-4505-bcc9-99a59c526f1f.png)

aka not having full cluster admin. So it at least got `oidc-login` working.

**Comment by jtagcat** [comment]
It works with autoDep=on as well. `oidc-login` wasn't in PATH? Though I got different behaviour depending on if I thought it was and wasn't before. Might've been the difference between reloading and actually restarting VSCode.

What does `cloudcode.customApplications` do? It seems undocumented.

**Comment by davidponder** [comment]
Glad to hear that `oidc-login` is now working! 

For your current issue, you've got it right that it comes down to the account not having full cluster admin privileges. This typically is configured in your .kubeconfig file, and might have a similar fix to [this StackOverflow post.](https://stackoverflow.com/questions/67151953/forbidden-resource-in-api-group-at-the-cluster-scope) The folks over at the [kubectl Github repository](https://github.com/kubernetes/kubectl) could probably help more than I could in fixing that issue!


For your follow-up question:
`cloudcode.customApplications` is a setting which allows for users to point to custom paths during the `>Cloud Code: New Application` command pallete command. It can be an array of objects, specified as such in. your `settings.json` file:

```
"cloudcode.customApplications": [
    {
      "repoUrl": "https://github.com/my/github/repo/url",
      "branchName": "sample-branch",
      "localPath": "/xxx/xxx/my/local/path"
    }
  ],
```

These selections show up as a follow-up action after selecting `>Cloud Code: New Application` > `Custom Application` (see below):
<img width="617" alt="Screen Shot 2022-11-17 at 2 12 55 PM" src="https://user-images.githubusercontent.com/22482315/202571423-2e0d5aca-65e4-4bde-bf87-b2525dc03c6f.png">

After looking at the tooltip for this setting, I've added a work item on our end to add a better tooltip since the current one does not do a great job at conveying this functionality; thank you for calling this out!

It seems like this has fixed the original issue, so I'll close this issue for now. Please feel free to re-open if you have any follow-up questions or suggestions. Thanks!
