### ISSUE TITLE
Switching Projects Doesn't Affect CLI Project

### ISSUE THREAD

**Issue by davidarice** [GoogleCloudPlatform/cloud-code-vscode#868]
Cloud Code Extension version:
v2.1.1

VSCode version:
1.84.2 (Universal)

OS: 
MacOS 13.6

Cloud SDK:
firebase-tools@12.9.1

Currently, if I switch projects using the UI the change is not reflected in the Firebase CLI. I can have the extension set to one project, but still use firebase CLI to switch to another. Is this normal? 

I would expect that switching projects in the UI would also switch the project in the CLI.

I have a production project and dev project, and I don't want to accidentally push my dev brach into production.

**Comment by j-windsor** [comment]
Hello,

This is by design. Users would not expect UX in VS Code to change something outside of VS Code like a CLI configuration, and this could result in some unexpected and harmful effects. Think: You deploy something you thought was to a dev environment but you're actually deploying to prod environment because the project changed in an unexpected way.

Please reopen if you have any additional questions.
